apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: {{ .Values.namespace.name }}
  labels:
    app: nginx
    {{- include "nginx-learning.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.nginx.replicaCount }}
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        {{- include "nginx-learning.labels" . | nindent 8 }}
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag }}"
          imagePullPolicy: {{ .Values.nginx.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.nginx.service.port }}
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            {{- toYaml .Values.nginx.resources | nindent 12 }}
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true
            - name: telemetry-ui
              mountPath: /usr/share/nginx/html/telemetry
              readOnly: true
            - name: nginx-logs
              mountPath: /var/log/nginx
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
        - name: telemetry-ui
          configMap:
            name: nginx-telemetry-ui
        - name: nginx-logs
          emptyDir: {}
