apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-telemetry-ui
  namespace: {{ .Values.namespace.name }}
  labels:
    app: nginx
    {{- include "nginx-learning.labels" . | nindent 4 }}
data:
  index.html: |
{{ .Files.Get "files/telemetry/index.html" | indent 4 }}
