play.http.secret.key = "dev-secret-change-me-please-rotate-32bytes-min"
play.http.router = "router.Routes"

play.application.loader = "play.inject.guice.GuiceApplicationLoader"


play.server.http.port = 9000
