spring.application.name=orders-service

server.port=8080

management.endpoints.web.exposure.include=health,info
spring.sleuth.sampler.probability=1.0

logging.file.name=logs/orders-service.log
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %5p [service=${spring.application.name:unknown},traceId=%X{traceId:-},spanId=%X{spanId:-}] [%thread] %logger{36} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss.SSS} %5p [service=${spring.application.name:unknown},traceId=%X{traceId:-},spanId=%X{spanId:-}] [%thread] %logger{36} - %msg%n
