apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-selector-lab
  namespace: k8s-lab
  labels:
    app: node-selector-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-selector-lab
  template:
    metadata:
      labels:
        app: node-selector-lab
    spec:
      nodeSelector:
        disktype: nvme
      containers:
        - name: nginx
          image: nginx:1.27-alpine
          ports:
            - containerPort: 80
