apiVersion: apps/v1
kind: Deployment
metadata:
  name: probe-lab
  namespace: k8s-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: probe-lab
  template:
    metadata:
      labels:
        app: probe-lab
    spec:
      containers:
        - name: nginx
          image: nginx:1.27-alpine
          ports:
            - containerPort: 80
              name: http
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 3
            periodSeconds: 10
