apiVersion: apps/v1
kind: Deployment
metadata:
  name: netpol-web
  namespace: k8s-lab
  labels:
    app: netpol-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netpol-web
  template:
    metadata:
      labels:
        app: netpol-web
        role: backend
    spec:
      containers:
        - name: nginx
          image: nginx:1.27-alpine
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: netpol-web
  namespace: k8s-lab
spec:
  selector:
    app: netpol-web
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netpol-client
  namespace: k8s-lab
  labels:
    app: netpol-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netpol-client
  template:
    metadata:
      labels:
        app: netpol-client
        role: client
    spec:
      containers:
        - name: curl
          image: curlimages/curl:8.5.0
          command: ["sleep", "3600"]
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-client-to-web
  namespace: k8s-lab
spec:
  podSelector:
    matchLabels:
      role: backend
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              role: trusted-client
