apiVersion: apps/v1
kind: Deployment
metadata:
  name: rollout-lab
  namespace: k8s-lab
  labels:
    app: rollout-lab
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rollout-lab
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: rollout-lab
        version: v1
    spec:
      containers:
        - name: web
          image: nginx:1.27-alpine
          ports:
            - containerPort: 80
              name: http
          readinessProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 3
