spring.application.name=liquibase-demo

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/liquibase_demo}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:demo}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:demo}

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

server.port=8080
