input {
  file {
    path => "/Users/jamesking/work/drawer2/Springboot/kibana/projects/log-sample-generator-app/log-samples/*.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
  }
}

filter {
  grok {
    match => {
      "message" => "%{TIMESTAMP_ISO8601:log_timestamp}\s+%{LOGLEVEL:log_level}\s+\[service=%{DATA:service_name},traceId=%{DATA:trace_id},spanId=%{DATA:span_id}\]\s+\[%{DATA:thread_name}\]\s+%{DATA:logger_name}\s+-\s+%{GREEDYDATA:log_message}"
    }
  }

  date {
    match => [ "log_timestamp", "yyyy-MM-dd HH:mm:ss.SSS" ]
    target => "@timestamp"
  }

  mutate {
    remove_field => [ "host", "path", "event", "log_timestamp" ]
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "springboot-logs-%{+YYYY.MM.dd}"
  }

  stdout {
    codec => rubydebug
  }
}